baseballs/urls.py
from django.urls import path

from . import views


app_name = 'baseballs'
urlpatterns = [
    path('index', views.set_index, name='set_index'),
    path('change_index1', views.change_index1, name='change_index1'),
    path('remove', views.remove, name='remove'),
    path('get_index', views.get_index, name='get_index'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    
    # 투수쪽
    path('index2', views.set_index2, name = 'set_index2'),
    path('change_index2', views.change_index2, name='change_index2'),
    path('get_index2', views.get_index2, name='get_index2'),
    path('autocomplete2', views.autocomplete2, name='autocomplete2'),

    # rank 
    path('b_rank', views.b_rank, name = 'b_rank'),
    path('p_rank', views.p_rank, name = 'p_rank'),

    # rank 비교 
    path('b_com', views.b_com, name = 'b_com'),
    path('p_com', views.p_com, name = 'p_com'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('baseballs/', include('baseballs.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path, include

from . import views


app_name = 'posts'
urlpatterns = [    
    path('community', views.index, name='index'),
    path('notice', views.index2, name='index2'),
    path('customer', views.index3, name='index3'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/update/', views.update, name='update'),
    # path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('search/', views.search, name='search'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_likes/', views.comment_likes, name='comment_likes'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_dislikes/', views.comment_dislikes, name='comment_dislikes'),
]

baseballs/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

baseballs/views.py
from django.shortcuts import render, redirect
# from .models import WeeklyBattingInfo
import yaml
import pandas as pd
import pymysql


from django.views.decorators.http import require_GET
from django.http import JsonResponse
from django.http import HttpResponse

# db정보 가져오기
with open('./yamls/sql_info.yaml') as f:

    info = yaml.load(f, Loader=yaml.FullLoader)

host = info['MARIADB']['IP']
user = info['MARIADB']['USER']
passwd=info['MARIADB']['PASSWD']
db = info['MARIADB']['DB']
port = info['MARIADB']['PORT']


##test 


def get_autodata():
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select concat(A.player_name,' ',A.team,' ',B.player_birth, ' ' ,A.player_ID) as data from (
        select player_ID ,player_name, GROUP_CONCAT(DISTINCT TEAM) as team from batting_info bi
        group by player_ID ,player_name ) A join player_birth B on A.player_ID = B.player_ID  
    '''
    cur.execute(sql)
    result = cur.fetchall()
    auto_data = pd.DataFrame(result)
    # print(auto_data)
    return auto_data


def get_autodata2():
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select concat(A.player_name,' ',A.team,' ',B.player_birth, ' ' ,A.player_ID) as data from (
        select player_ID ,player_name, GROUP_CONCAT(DISTINCT TEAM) as team from pitching_info bi
        group by player_ID ,player_name ) A join player_birth B on A.player_ID = B.player_ID 
    '''
    cur.execute(sql)
    result = cur.fetchall()
    auto_data = pd.DataFrame(result)
    # print(auto_data)
    return auto_data


def get_data(p_name,p_id):
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select week,sum(H) as `H` from weekly_batting_info
            where 1=1
            and player_name = '{p_name}'
            and player_ID = '{p_id}'
            group by week
    '''
    cur.execute(sql)
    result = cur.fetchall()
    batting = pd.DataFrame(result)
    print(batting)
    conn.close()
    return batting


def change_data(p_name,p_id,idx):
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select week,sum({idx}) as `H` from weekly_batting_info
            where 1=1
            and player_name = '{p_name}'
            and player_ID = '{p_id}'
            group by week
    '''
    cur.execute(sql)
    result = cur.fetchall()
    batting = pd.DataFrame(result)
    print(batting)
    conn.close()
    return batting

def get_data2(p_name,p_id):
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select week, sum(ER) / sum(IP) * 9 as `ERA`  from weekly_pitching_info wpi 
            where 1=1
            and player_name = '{p_name}'
            and player_ID ='{p_id}'
            group by week
    '''
    cur.execute(sql)
    result = cur.fetchall()
    pitching = pd.DataFrame(result)
    print(pitching)
    conn.close()
    return pitching

def change_data2(p_name,p_id,idx):
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select week,sum({idx}) as `ERA` from weekly_pitching_info
            where 1=1
            and player_name = '{p_name}'
            and player_ID = '{p_id}'
            group by week
    '''
    print(sql)
    cur.execute(sql)
    result = cur.fetchall()
    pitching = pd.DataFrame(result)
    print(pitching)
    conn.close()
    return pitching



def get_rank_data(player_type):
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select * from rank_info 
    where 1=1
    and player_type = '{player_type}'
    order by total_point DESC '''
    cur.execute(sql)
    result = cur.fetchall()
    rank = pd.DataFrame(result)
    return rank

def get_week():
    conn = pymysql.connect(host = host, user = user, passwd=passwd, db = db, charset='utf8', port = port, cursorclass=pymysql.cursors.DictCursor)
    cur = conn.cursor()
    sql = f'''select week  from weekly_batting_info
            group by week 
    '''
    cur.execute(sql)
    result = cur.fetchall()
    week = pd.DataFrame(result)
    conn.close()
    return week



week = get_week()
week_list = week['week'].to_list()
auto_data = get_autodata()
auto_data2 = get_autodata2()

def set_index(request):

    request.session['p_name'] = ['강백호']
    request.session['p_id'] = ['68050']
    idx = '안타'
    request.session['idx'] = idx
    
    
    p_name = request.session.get('p_name')
    p_id = request.session.get('p_id')
    hit_data = get_data('강백호','68050')
    hit_data = pd.merge(hit_data[['week','H']], week, on = 'week', how='right')
    hit_data_list = hit_data['H'].fillna(0).astype(int).to_list()
    request.session['hit_data'] = [hit_data_list]
    hit = request.session.get('hit_data')

    context = {
                'idx' : idx,
                'p_name' : p_name,
                'p_id' : p_id,
                'zip_info' : zip(p_name,p_id),
                'week' : week_list,
                'result' : zip(p_name,hit,p_id),
            }

    return render(request, 'baseballs/index.html',context)

def get_index(request):
    
    # 기존 리스트 
    b_name = request.session.get('p_name', [])
    b_hit = request.session.get('hit_data', [])
    b_id = request.session.get('p_id',[])

    idx = request.session.get('idx')
    
    if idx == '안타':
        col = 'H'
    elif idx == '타점':
        col = 'RBI'
    elif idx == '홈런':
        col = 'HR'
    
    # 신규 선수 이름 
    re_val = request.POST['add_name'].split(' ')


    add_name = re_val[0]

    ############################################################
    ## 자동완성을 사용하지 않을 시 화면에 경고창 표시가 필요함 ! ##
    ############################################################
    add_id = re_val[5]
    hit_data = change_data(add_name,add_id,col)

    # 1. 조회된선수가 없는 경우 -> 기존 값 반환 
    if len(hit_data) == 0:
        context = {
                'idx' : idx,
                'p_name' : b_name,
                'p_id' : b_id,
                'zip_info' : zip(b_name,b_id),
                'week' : week_list,
                'result' : zip(b_name,b_hit,b_id),
            }
        return render(request, 'baseballs/index.html',context)

    # 2. 조회한선수가 이미 있는 경우 -> 기존 값 반환 
    elif add_id in request.session['p_id']:
        context = {
                'idx' : idx,
                'p_name' : b_name,
                'p_id' : b_id,
                'zip_info' : zip(b_name,b_id),
                'week' : week_list,
                'result' : zip(b_name,b_hit,b_id),
            }
        return render(request, 'baseballs/index.html',context)
    
    # 3. 조회선수 추가
    else:
        # 신규 선수 h list 
        hit_data = pd.merge(hit_data[['week','H']], week, on = 'week', how='right')
        hit_data_list = hit_data['H'].fillna(0).astype(int).to_list()

        # session 추가
        b_name.append(add_name)
        b_hit.append(hit_data_list)
        b_id.append(add_id)
        request.session['p_name'] = b_name
        request.session['hit_data'] = b_hit
        request.session['p_id'] = b_id

        p_name = request.session.get('p_name')
        p_id = request.session.get('p_id')
        hit = request.session.get('hit_data')


        context = {
                    'idx' : idx,
                    'p_name' : p_name,
                    'p_id' : p_id,
                    'zip_info' : zip(p_name,p_id),
                    'week' : week_list,
                    'result' : zip(p_name,hit,p_id),
                }
        return render(request, 'baseballs/index.html',context)


def change_index1(request):

    idx = request.POST['selected_value']
    
    request.session['idx'] = idx
    
    if idx == '안타':
        col = 'H'
    elif idx == '타점':
        col = 'RBI'
    elif idx == '홈런':
        col = 'HR'
    
    p_name = request.session.get('p_name')
    p_id = request.session.get('p_id')
    
    
    hit_list = []
    for pname,pid in zip(p_name,p_id):
        
        hit_data = change_data(pname,pid,col)
        hit_data = pd.merge(hit_data[['week','H']], week, on = 'week', how='right')
        hit_list.append(hit_data['H'].fillna(0).astype(int).to_list())
        
    request.session['hit_data'] = hit_list        

    context = {
                'idx' : idx,
                'p_name' : p_name,
                'p_id' : p_id,
                'zip_info' : zip(p_name,p_id),
                'week' : week_list,
                'result' : zip(p_name,hit_list,p_id),
            }
    
    
    
    return render(request,'baseballs/index.html', context)



def remove(request):
    
    idxs = request.session.get('idx')
    
    #제거 대상
    if 'remove_name' in request.POST:
        remove_id = request.POST['remove_name']
        
        # 기존 리스트 불러오기
        b_name = request.session.get('p_name', [])
        b_hit = request.session.get('hit_data', [])
        b_id = request.session.get('p_id',[])


        # 제거 대상 idx 찾기 
        try:
            idx = b_id.index(remove_id)
        
        # 제거 페이지 새로고침시 에러 회피를 위한 부분
        except:
            p_name = request.session.get('p_name')
            hit = request.session.get('hit_data')
            p_id = request.session.get('p_id')

            context = {
                        'idx' : idxs,
                        'p_name' : p_name,
                        'week' : week_list,

baseballs/templates/baseballs/index.html
{% extends 'base.html' %}


<!-- 1. static 사용 -->
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/baseballs/baseballindex.css' %}">
{% endblock style %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
  
</head>
<body>
  <!-- 4. 사이트 html 하단 figure 태그 -->
	<figure class="highcharts-figure">
    <div class="chart-container">
      <form id="select-form" method="post" action="{% url 'baseballs:change_index1' %}">
        {% csrf_token %}
        <select id="index-select" name="selected_value"> 
            <option value="안타" {% if idx == '안타' %}selected{% endif %}>안타</option>
            <option value="홈런" {% if idx == '홈런' %}selected{% endif %}>홈런</option>
            <option value="타점" {% if idx == '타점' %}selected{% endif %}>타점</option>
        </select>
      </form>
  </div>
    <div id="container">Loading...</div>
      <form method="post" action="{% url 'baseballs:remove' %}" >
        {% csrf_token %}
        {% for name,id in zip_info %}
        <spann>
        <button name = 'remove_name' type = 'submit' value="{{id}}" class  = 'baseballs__index--btn1' >{{name}}({{id}}) X</button>
        </spann>
        {% endfor %}
      </form>
      <form  id = 'index-form' method = 'post' action="{% url 'baseballs:get_index' %}">

        {% csrf_token %}
        <div class = 'baseballs__index--div1'>
        <input type="text" id="search-input" name = 'add_name' class = 'baseballs__index--tag1' placeholder="자동완성 형태로 입력해주세요">
        </div>
        <button id="compare" class  = 'baseballs__index--btn2' >비교</button>
      </form>
      
    </figure>


    
    
    
    <script>  
    var $ = jQuery.noConflict();

$(function() {
  // 자동완성 데이터를 가져올 URL에서 데이터를 비동기적으로 가져옴
  $.get("autocomplete", function(data) {
    // 데이터를 가져온 후에 Autocomplete 위젯을 설정
    $("#search-input").autocomplete({
      source: data, // 가져온 데이터를 자동완성 데이터로 설정
      minLength: 1 // 최소 입력 문자열 길이
    });

    // 검증 및 form 제출을 위한 이벤트 핸들러 등록
    document.getElementById('compare').addEventListener('click', function(event) {
      event.preventDefault(); // Prevent the default form submission behavior
      var inputValue = document.getElementById('search-input').value;
      console.log(inputValue)

      // input 값이 자동완성 목록에 없는 경우
      var autocompleteOptions = data; // 가져온 데이터 사용
      console.log(autocompleteOptions)
      if (!autocompleteOptions.includes(inputValue)) {
        alert('자동완성 목록에 있는 데이터를 입력해주세요.');
        return;
      }

      // input 값이 있는 경우 form 제출
      document.getElementById('index-form').submit();
    });

    document.getElementById('index-select').addEventListener('change', function() {
      document.getElementById('select-form').submit();
    });
  });
});

      var $ = jQuery.noConflict();
      $(function() {
        // $ 기호를 사용하는 코드를 이곳에 작성합니다.
        $("#search-input").autocomplete({
          source: "autocomplete", // 자동완성 데이터를 가져올 URL
          minLength: 1 // 최소 입력 문자열 길이
        });
      });
      </script>
    <script>

      var machart = Highcharts.chart('container', {
        chart: {
          type: 'spline'
        },
        title: {
          text: '주간 {{idx}}'
        },
        // subtitle: {
        //   text: 'Source: WorldClimate.com'
        // },
        xAxis: {
          categories: [{% for i in week %}{{i}}, {% endfor %}],
        },
        yAxis: {
          min: 0,    // Y 축의 최소값 설정
          max: 20,  // Y 축의 최대값 설정
          title: {
            text: '{{idx}}'
          },
          labels: {
            formatter: function () {
              return this.value + '개';
            }
          }
        },
        tooltip: {
          crosshairs: true,
          shared: true
        },
        plotOptions: {
          spline: {
            marker: {
              radius: 4,
              lineColor: '#666666',
              lineWidth: 1
            }
          }
        },
        series: [


        // 이부분 for문으로 
        {% for name,hit,pid in result %} 
        {
          name: '{{name}}({{pid}})',  
          data: {{hit}}
        },
        {% endfor %}
      ]
      });
    
    </script>
</body>
</html>

{% endblock content %}

baseballs/templates/baseballs/index2.html
{% extends 'base.html' %}


<!-- 1. static 사용 -->
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/baseballs/baseballindex.css' %}">
{% endblock style %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>   
    
</head>
<body>
  
	<!-- 4. 사이트 html 하단 figure 태그 -->
	<figure class="highcharts-figure">
    <div class="chart-container">
      <form id="select-form" method="post" action="{% url 'baseballs:change_index2' %}">
        {% csrf_token %}
        <select id="index-select" name="selected_value"> 
            <option value="방어율" {% if idx == '방어율' %}selected{% endif %}>방어율</option>
            <option value="삼진" {% if idx == '삼진' %}selected{% endif %}>삼진</option>
            <option value="피안타" {% if idx == '피안타' %}selected{% endif %}>피안타</option>
            <option value="피홈런" {% if idx == '피홈런' %}selected{% endif %}>피홈런</option>
        </select>
      </form>
    </div>
      <div id="container">test</div>
      <form method="post" action="{% url 'baseballs:remove' %}" >
        {% csrf_token %}
        {% for name,id in zip_info %}
        <spann>
        <button name = 'remove_name2' type = 'submit' value="{{id}}" class  = 'baseballs__index--btn1' >{{name}}({{id}} X</button>
        </spann>
        {% endfor %}
      </form>
      <form id = 'index-form' method = 'post' action="{% url 'baseballs:get_index2' %}">

        {% csrf_token %}
        <div class = 'baseballs__index--div1'>
        <input type="text" id="search-input" name = 'add_name' class = 'baseballs__index--tag1' placeholder="자동완성 형태로 입력해주세요">
        </div>
        <button id="compare" class  = 'baseballs__index--btn2' >비교</button>
      </form>
    
    </figure>

    
    
    
    <script>
      var $ = jQuery.noConflict();

$(function() {
  // 자동완성 데이터를 가져올 URL에서 데이터를 비동기적으로 가져옴
  $.get("autocomplete2", function(data) {
    // 데이터를 가져온 후에 Autocomplete 위젯을 설정
    $("#search-input").autocomplete({
      source: data, // 가져온 데이터를 자동완성 데이터로 설정
      minLength: 1 // 최소 입력 문자열 길이
    });

    // 검증 및 form 제출을 위한 이벤트 핸들러 등록
    document.getElementById('compare').addEventListener('click', function(event) {
      event.preventDefault(); // Prevent the default form submission behavior
      var inputValue = document.getElementById('search-input').value;
      console.log(inputValue)

      // input 값이 자동완성 목록에 없는 경우
      var autocompleteOptions = data; // 가져온 데이터 사용
      console.log(autocompleteOptions)
      if (!autocompleteOptions.includes(inputValue)) {
        alert('자동완성 목록에 있는 데이터를 입력해주세요.');
        return;
      }

      // input 값이 있는 경우 form 제출
      document.getElementById('index-form').submit();
    });

    document.getElementById('index-select').addEventListener('change', function() {
      document.getElementById('select-form').submit();
    });
  });
});


      document.getElementById('index-select').addEventListener('change', function() {
        document.getElementById('select-form').submit();
    });


      var $ = jQuery.noConflict();
      $(function() {
        // $ 기호를 사용하는 코드를 이곳에 작성합니다.
        $("#search-input").autocomplete({
          source: "autocomplete2", // 자동완성 데이터를 가져올 URL
          minLength: 1 // 최소 입력 문자열 길이
        });
      });
      </script>
    <script>

      var machart = Highcharts.chart('container', {
        chart: {
          type: 'spline'
        },
        title: {
          text: '주간 {{idx}}'
        },
        // subtitle: {
        //   text: 'Source: WorldClimate.com'
        // },
        xAxis: {
          categories: [{% for i in week %}{{i}}, {% endfor %}],
        },
        yAxis: {
          {% if idx == '방어율' %} 

          min : -5,
          title: {
            text: '{{idx}}',
          },
          labels: {
            formatter: function () {
              return this.value ;
            }
          }
          {% else %} 

          min : 0,
          max : 20,  
          title: {
            text: '{{idx}}',
          },     
          labels: {
            formatter: function () {
              return this.value + '개';
            }
          }

          {% endif %}
          
        },
        tooltip: {
          crosshairs: true,
          shared: true
        },
        plotOptions: {
          spline: {
            marker: {
              radius: 4,
              lineColor: '#666666',
              lineWidth: 1
            }
          }
        },
        series: [
        // 이부분 for문으로 
        {% for name,pit,pid in result %} 
        {
          name: '{{name}}({{pid}})',  
          data: [
                {% for p in pit %} 
                      {% if p == -1.0 %} 
                      
                        {
                        y: -1.0,
                        marker: {
                          fillColor: 'red'
                        }
                        }, 
                      {% else %} 
                        {{p}}, 
                      {% endif %}
                {% endfor %}
        ]
        },     
        {% endfor %}
      ]
      });
    
    </script>
</body>
</html>

{% endblock content %}

baseballs/templates/baseballs/rank.html
{% extends 'base.html' %}

{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'css/posts/postsindex.css' %}">
{% endblock style %}

{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>

{% endblock content %}