accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
]

baseballs/urls.py
from django.urls import path

from . import views


app_name = 'baseballs'
urlpatterns = [
    path('index', views.set_index, name='set_index'),
    path('change_index1', views.change_index1, name='change_index1'),
    path('remove', views.remove, name='remove'),
    path('get_index', views.get_index, name='get_index'),
    path('autocomplete', views.autocomplete, name='autocomplete'),
    
    # 투수쪽
    path('index2', views.set_index2, name = 'set_index2'),
    path('change_index2', views.change_index2, name='change_index2'),
    path('get_index2', views.get_index2, name='get_index2'),
    path('autocomplete2', views.autocomplete2, name='autocomplete2'),

    # rank 
    path('b_rank', views.b_rank, name = 'b_rank'),
    path('p_rank', views.p_rank, name = 'p_rank'),

    # rank 비교 
    path('b_com', views.b_com, name = 'b_com'),
    path('p_com', views.p_com, name = 'p_com'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('baseballs/', include('baseballs.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path, include

from . import views


app_name = 'posts'
urlpatterns = [    
    path('community', views.index, name='index'),
    path('notice', views.index2, name='index2'),
    path('customer', views.index3, name='index3'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/update/', views.update, name='update'),
    # path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('search/', views.search, name='search'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_likes/', views.comment_likes, name='comment_likes'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_dislikes/', views.comment_dislikes, name='comment_dislikes'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />
    <title>Document</title>
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
    
    <!-- jQuery 라이브러리 로드 -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
      // $ 기호를 jQuery로 설정
      jQuery.noConflict();
    </script>

    <!-- jQuery UI 라이브러리 로드 -->
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">

    <!-- axios 로드 -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- 2. 사이트 html 하단 script 태그 위치 -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}" rel="stylesheet">
    {% block style %}    
    {% endblock style %}
</head>
<body>
    {% include 'nav.html' %}
    <div class='base--warp'>
        {% block content %}
        {% endblock content %}
        <button id="theme-toggle" type="button" class="darkbtn text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
            <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
            <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
        </button>
    </div>
    {% include 'footer.html' %}
    
    {% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>
    
    {% block script %}
    {% endblock script %}
</body>
</html>

templates/default.html
{% extends 'base.html' %}


<!-- 1. static 사용 -->
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/baseballs/baseballindex.css' %}">
{% endblock style %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
  
</head>
<body>
    <section>
        <div>
            <table border="1">
                <thead>
                    <tr>
                        {% for column in dataframe.columns %}
                        <th>{{ column }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for index, row in dataframe.iterrows %}
                    <tr>
                        
                        {% for column in row %}
                        <td>{{column}}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


    </section>


</body>
</html>

{% endblock content %}

templates/footer.html
{% load static %}


<footer class="bg-gray-200 dark:bg-gray-700">
  <div class="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
      <div class="md:flex md:justify-between">
        <div class="mb-6 md:mb-0">
            <a href="{% url 'index' %}" class="flex items-center">
                <img src="{% static 'img/5.png' %}" class="h-8 mr-3" style = "background: transparent; display: block; width: 10%; height: 15%;" alt="BW" />
                <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">BW</span>
            </a>
        </div>
        <div class="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
            <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                <ul class="text-gray-500 dark:text-gray-400 font-medium">
                    <li class="mb-4">
                        <a href="https://flowbite.com/" class="hover:underline">Flowbite</a>
                    </li>
                    <li>
                        <a href="https://tailwindcss.com/" class="hover:underline">Tailwind CSS</a>
                    </li>
                </ul>
            </div>
            <div>
                <h2 class="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Follow us</h2>
                <ul class="text-gray-500 dark:text-gray-400 font-medium">
                    <li class="mb-4">
                        <a href="https://gitlab.com/sum9611/gitlab_baseball_web" class="hover:underline ">Gitlab</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
    <div class="sm:flex sm:items-center sm:justify-between">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400"> 
        </span>
        <div class="flex mt-4 space-x-5 sm:justify-center sm:mt-0">
            <a href="https://gitlab.com/sum9611/gitlab_baseball_web" class="text-gray-500 hover:text-gray-900 dark:hover:text-white">
                <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M10 .333A9.911 9.911 0 0 0 6.866 19.65c.5.092.678-.215.678-.477 0-.237-.01-1.017-.014-1.845-2.757.6-3.338-1.169-3.338-1.169a2.627 2.627 0 0 0-1.1-1.451c-.9-.615.07-.6.07-.6a2.084 2.084 0 0 1 1.518 1.021 2.11 2.11 0 0 0 2.884.823c.044-.503.268-.973.63-1.325-2.2-.25-4.516-1.1-4.516-4.9A3.832 3.832 0 0 1 4.7 7.068a3.56 3.56 0 0 1 .095-2.623s.832-.266 2.726 1.016a9.409 9.409 0 0 1 4.962 0c1.89-1.282 2.717-1.016 2.717-1.016.366.83.402 1.768.1 2.623a3.827 3.827 0 0 1 1.02 2.659c0 3.807-2.319 4.644-4.525 4.889a2.366 2.366 0 0 1 .673 1.834c0 1.326-.012 2.394-.012 2.72 0 .263.18.572.681.475A9.911 9.911 0 0 0 10 .333Z" clip-rule="evenodd"/>
                </svg>
                <span class="sr-only">GitHub account</span>
            </a>
            
        </div>
    </div>
  </div>
</footer>

templates/nav.html
{% load static %}



<nav class="bg-white-0 border-gray-200 dark:bg-gray-900">
    <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
        <a href="{% url 'index' %}" class="flex items-center">
            <img src="{% static 'img/5.png' %}" class="h-8 mr-3" style = "background: transparent; display: block; width: 10%; height: 15%;" alt="BW" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">BW</span>
        </a>
        <div class="flex items-center">
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="mr-6 text-sm  text-blue-600 dark:text-blue-500 hover:underline">logout</a>
            {% else %}
            <a href="{% url 'accounts:login' %}" class="mr-6 text-sm  text-blue-600 dark:text-blue-500 hover:underline">Sign in</a>
            <a href="{% url 'accounts:signup' %}" class="text-sm  text-blue-600 dark:text-blue-500 hover:underline">Sign up</a>
            {% endif %}
        </div>
    </div>
</nav>
<nav class="bg-gray-200 dark:bg-gray-700">
    <div class="max-w-screen-xl px-4 py-3 mx-auto">
        <div class="flex items-center">
            <ul class="flex flex-row font-medium mt-0 mr-6 space-x-8 text-sm">
                <li>
                    <a href="{% url 'index' %}" class="text-gray-900 dark:text-white hover:underline" aria-current="page">메인</a>
                </li>
                <li>
                    <button id="weeklyIndex" data-dropdown-toggle="weeklyIndexdropdown" class="text-gray-900 dark:text-white hover:underline" type="button">주간 지표</button>
                    <!-- Dropdown menu -->
                    <div id="weeklyIndexdropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="weeklyIndex">
                            <li>
                                <a href="{% url 'baseballs:set_index' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">타자</a>
                            </li>
                            <li>
                                <a href="{% url 'baseballs:set_index2' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">투수</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <button id="weeklyIndex" data-dropdown-toggle="rankIndexdropdown" class="text-gray-900 dark:text-white hover:underline" type="button">누적 랭킹</button>
                    <!-- Dropdown menu -->
                    <div id="rankIndexdropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="weeklyIndex">
                            <li>
                                <a href="{% url 'baseballs:b_rank' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">타자</a>
                            </li>
                            <li>
                                <a href="{% url 'baseballs:p_rank' %}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">투수</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="{% url 'posts:index' %}" class="text-gray-900 dark:text-white hover:underline">커뮤니티</a>
                </li>
                <li>
                    <a href="{% url 'posts:index2' %}" class="text-gray-900 dark:text-white hover:underline">공지사항</a>
                </li>
                <li>
                    <button id="customerCenter" data-dropdown-toggle="customerCenterdropdown" class="text-gray-900 dark:text-white hover:underline" type="button">고객센터</button>
                    <!-- Dropdown menu -->
                    <div id="customerCenterdropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
                        <ul class="navbar__submenu py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="customerCenter">
                            <li>
                                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">1:1 문의</a>
                            </li>
                            <li>
                                <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">버그/오류 제보</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>