config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('baseballs/', include('baseballs.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path, include

from . import views


app_name = 'posts'
urlpatterns = [    
    path('community', views.index, name='index'),
    path('notice', views.index2, name='index2'),
    path('customer', views.index3, name='index3'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/update/', views.update, name='update'),
    # path('<int:post_pk>/delete/', views.delete, name='delete'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('search/', views.search, name='search'),
    path('<int:post_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', views.comment_update, name='comment_update'),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_likes/', views.comment_likes, name='comment_likes'),
    # path('<int:post_pk>/comments/<int:comment_pk>/comment_dislikes/', views.comment_dislikes, name='comment_dislikes'),
]

posts/models.py
import uuid
from django.db import models
from django.conf import settings
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    content = RichTextUploadingField(blank=True,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    view_count = models.PositiveIntegerField(default=0)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')


class PostComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    anonymous_ip = models.CharField(max_length = 50, default = '0')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_pw = models.CharField(max_length=256, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_postcomments')
    dislike_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='dislike_postcomments')

posts/forms.py
from django import forms
from .models import Post, PostComment
from ckeditor_uploader.widgets import CKEditorUploadingWidget

class CustomPost(forms.ModelForm):
    title = forms.CharField(
        label=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목',
                'class': 'my-2 fs-5 p-2 focus:outline-[#A2E04E] outline-offset-2 rounded',
                'style': 'width: 100%;',
            }
        )
    )
    
    content = forms.CharField(
        widget=CKEditorUploadingWidget(
            attrs={
                'placeholder': '내용',
            }
        ),
        label=''
    )

    category = forms.ChoiceField(
        choices=[('공지', '공지'), ('문의', '문의'), ('타자', '타자'), ('투수', '투수'), ('자유', '자유')],
        widget=forms.Select(
            attrs={
                'class': 'form-control'
            }
        )
    )

    class Meta:
        model = Post
        fields = ['title', 'category', 'content',]
        widgets = {
            'content': CKEditorUploadingWidget(),
        }


class CustomPostComment(forms.ModelForm):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': '내용을 입력해 주세요.',
                'class': 'comment-content',
                'id': 'comment-content',
                'style': 'width: 100%; height: 100%; resize: none;',
                'aria-describedby': 'comment-username-description',
            }
        ),
        label=''
    )

    comment_pw = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Password',
                'class': 'comment-pw',
                'id': 'comment-pw',
                'style': 'width: 100%; height: 100%; resize: none;',
                'autocomplete': 'new-password',
            }
        ),
        required=False,
    )
    
    class Meta:
        model = PostComment
        fields = ['content', 'comment_pw']

posts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.hashers import make_password, check_password
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from .models import Post, PostComment
from .forms import CustomPost, CustomPostComment
from django import forms
from django.contrib.auth.models import AnonymousUser
from django.http import HttpResponseRedirect
from .utils import get_client_ip

from bs4 import BeautifulSoup


# Create your views here.
User = get_user_model()

def get_first_image_from_content(content):
    soup = BeautifulSoup(content, 'html.parser')
    img_tag = soup.find('img')
    if img_tag:
        return img_tag['src']
    else:
        return None

def index(request):
    posts = Post.objects.all().order_by('-id')

    # 페이지네이션
    page = request.GET.get('page', '1')
    per_page = 10
    paginator = Paginator(posts, per_page)
    page_obj = paginator.get_page(page)

    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def index2(request):
    posts = Post.objects.all().order_by('-id')

    # 페이지네이션
    page = request.GET.get('page', '1')
    per_page = 10
    paginator = Paginator(posts, per_page)
    page_obj = paginator.get_page(page)

    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/notice.html', context)


def index3(request):
    posts = Post.objects.all().order_by('-id')

    # 페이지네이션
    page = request.GET.get('page', '1')
    per_page = 10
    paginator = Paginator(posts, per_page)
    page_obj = paginator.get_page(page)

    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/customercenter.html', context)


def search(request):
    query = request.GET.get('q')
    search_option = request.GET.get('search_option')

    if query and search_option:
        if search_option == 'title':
            filtered_posts = Post.objects.filter(title__contains=query).order_by('-id')
        elif search_option == 'author':
            filtered_posts = Post.objects.filter(user__username__icontains=query).order_by('-id')
        elif search_option == 'content':
            filtered_posts = Post.objects.filter(content__contains=query).order_by('-id')
        elif search_option == 'title_content':
            filtered_posts = Post.objects.filter(Q(title__contains=query) | Q(content__contains=query)).order_by('-id')
    else:
        filtered_posts = Post.objects.order_by('-id')

    # 페이지네이션
    page = request.GET.get('page', '1')
    per_page = 10
    paginator = Paginator(filtered_posts, per_page)
    page_obj = paginator.get_page(page)

    context = {
        'page_obj': page_obj,
        'query': query,
        'search_option': search_option,
    }
    return render(request, 'posts/index.html', context)


def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    postcomment_form = CustomPostComment()
    postcomments = post.postcomment_set.order_by('-id')

    # 포스트의 뷰 카운트 증가시키기
    post.view_count += 1
    post.save()
    
    prev_post = Post.objects.filter(pk__gt=post_pk).order_by('pk').first()
    next_post = Post.objects.filter(pk__lt=post_pk).order_by('-pk').first()

    # 페이지네이션
    page = request.GET.get('page', '1')
    per_page = 10
    paginator = Paginator(postcomments, per_page)
    page_obj = paginator.get_page(page)

    context = {
        'post': post,
        'postcomment_form': postcomment_form,
        'postcomments': postcomments,
        'prev_post': prev_post,
        'next_post': next_post,
        'page_obj': page_obj,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = CustomPost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = CustomPost()

    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user != post.user:
        return redirect('posts:detail', post.pk)
    
    if request.method == 'POST':
        form = CustomPost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post.save()
            return redirect('posts:detail', post.pk)
    else:
        form = CustomPost(instance=post)

    context = {
        'post': post,
        'form': form,
    }

    return render(request, 'posts/update.html', context)


@login_required
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user == post.user:
        post.delete()
    return redirect('posts:index')


@login_required
def likes(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
        
    if post.like_users.filter(pk=request.user.pk).exists():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    
    
    context = {
        'is_liked':is_liked,
        'like_count':post.like_users.count()
    }
    return JsonResponse(context)


def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    postcomment_form = CustomPostComment(request.POST)

    if postcomment_form.is_valid():
        postcomment = postcomment_form.save(commit=False)
        postcomment.post = post

        # 미인증 사용자일 경우 댓글 작성자 None 처리
        if request.user.is_authenticated:
            postcomment.user = request.user
            comment_pw = request.user.password
            postcomment.comment_pw = comment_pw
            
        else:
            postcomment.user = None
            postcomment.anonymous_ip = get_client_ip(request)

            # 비밀번호 확인
            comment_pw = request.POST.get('comment_pw')
            if not comment_pw and not request.user.is_authenticated:
                return HttpResponse('비밀번호를 입력해주세요')
        
            postcomment.comment_pw = make_password(comment_pw)

        postcomment.save()
        return redirect('posts:detail', post_pk)
    else:
        postcomment_form = CustomPostComment()
        
    context = {
        'post': post,
        'postcomment_form': postcomment_form,
    }

    return render(request, 'posts/detail.html', context)


def comment_update(request, post_pk, comment_pk):
    postcomment = PostComment.objects.get(pk=comment_pk)

    if request.method == 'POST':
        form = CustomPostComment(request.POST, instance=postcomment)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post_pk)
    else:
        form = CustomPostComment(instance=postcomment)

    context = {
        'form': form,
        'post_pk': post_pk,
        'comment_pk': comment_pk,
    }
    return render(request, 'posts/comment_update.html', context)


def comment_delete(request, post_pk, comment_pk):
    postcomment = PostComment.objects.get(pk=comment_pk)

    if request.method == 'POST':
        comment_pw = request.POST.get('comment_pw')

        if not comment_pw:
            return JsonResponse({'status': 'error', 'message': '비밀번호를 입력해주세요.'})
        
        if postcomment.user:
            if request.user.is_authenticated and postcomment.user == request.user:
                # 로그인한 사용자의 비밀번호를 확인하여 인증
                user = authenticate(request, username=request.user.username, password=comment_pw)
                if user is None:
                    return JsonResponse({'status': 'error', 'message': '비밀번호가 일치하지 않습니다.'})
                else:
                    # 비밀번호가 일치하면 댓글 삭제
                    postcomment.delete()
                    post_comments = PostComment.objects.filter(post=post_pk).count()
                    return redirect('posts:detail', post_pk)
            else:
                # 작성자가 아닌 경우 권한 오류 메시지 반환
                return JsonResponse({'status': 'error', 'message': '권한이 없습니다.'})
        else:
            # 익명 댓글인 경우 비밀번호를 확인하여 삭제
            if check_password(comment_pw, postcomment.comment_pw):
                postcomment.delete()
                post_comments = PostComment.objects.filter(post=post_pk).count()
                return redirect('posts:detail', post_pk)
            else:
                return JsonResponse({'status': 'error', 'message': '비밀번호가 일치하지 않습니다.'})
                
    else:
        return redirect('posts:detail', post_pk)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
{{ form.media }}
{% endblock style %}

{% block content %}
<form action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="제출">
</form>
{% endblock content %}

{% block script %}
{{ form.media }}
{% endblock script %}

posts/templates/posts/customercenter.html
{% extends 'base.html' %}

{% load static %}
{% load highlight_filter %}
{% load custom_filters %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/posts/postsindex.css' %}">
{% endblock style %}

{% block content %}
<section class="bg-white-0 dark:bg-gray-900">
  <div class="posts__index--warp">
    <div class="posts__index--header">
      <h1 class="posts__index--title dark:text-white">고객센터</h1>
      <a href="{% url 'posts:create' %}">
        <button type="button" class="posts__post--writebtn text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">글작성</button>
      </a>
    </div>
    <div class="posts__posts--listbox dark:text-white"> 
      <ul class="posts__posts--list">
        <li class="posts__posts--index">
          <p class="text1" style="width: 5%;">번호</p>
          <p class="text1" style="width: 10%;"></p>
          <p class="text1" style="width: 38%;">제목</p>
          <p class="text1" style="width: 15%;">작성자</p>
          <p class="text1" style="width: 15%;">작성일</p>
          <p class="text1" style="width: 8.5%;">추천</p>
          <p class="text1" style="width: 8.5%;">조회수</p>
        </li>
      </ul>
      <ul class="posts__posts--list">
        {% for post in page_obj %}
          <a href="{% url 'posts:detail' post.pk %}">
            <li class="posts__post--item {% if forloop.last %}last{% endif %}">
              <p class="posts__number text-center" style="width: 5%;">{{ post.pk }}</p>
              <p class="posts__number text-center" style="width: 10%;">[{{post.category}}]</p>
              {% if search_option == 'title' %}
                <p class="posts__title">{{ post.title|highlight:query|safe }}<span class="posts__index--titlecnt">{% if post.postcomment_set.count != 0 %}[{{ post.postcomment_set.count }}]{% else %}{% endif %}</span></p>
              {% else %}
                <p class="posts__title">{{ post.title }}<span class="posts__index--titlecnt">{% if post.postcomment_set.count != 0 %}[{{ post.postcomment_set.count }}]{% else %}{% endif %}</span></p>
              {% endif %}
              {% if search_option == 'author' %}
                <p class="posts__user text-center" style="width: 15%;">{{ post.user.username|highlight:query|safe }}</p>
              {% else %}
                <p class="posts__user text-center" style="width: 15%;">{{ post.user.username }}</p>
              {% endif %}
              <p class="posts__created text-center" style="width: 15%;">{{ post.created_at|date:"Y. m. d" }}</p>
              <p class="posts__created text-center" style="width: 8.5%;">{{ post.like_users.count }}</p>
              <p class="posts__created text-center" style="width: 8.5%;">{{ post.view_count }}</p>
            </li>
          </a>
        {% endfor %}
      </ul>
    </div>
    {% comment %} paginator {% endcomment %}
    <div class="pagination mt-4">
      <div class="mx-auto dark:text-white">
        {% if page_obj.has_previous %}
          <a href="?search_option={{ search_option }}&q={{ query }}&page=1" class="page__btn"><i class="bi bi-chevron-double-left" style="font-size: 15px;"></i></a>
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.previous_page_number }}" class="page__btn"><i class="bi bi-chevron-left" style="font-size: 15px; margin-right: 10px;"></i></a>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
          {% if page_number >= page_obj.number|add:'-5' and page_number <= page_obj.number|add:'4' %}
            {% if page_number == page_obj.number %}
              <span class="page__btn pagination__link--active">{{ page_number }}</span>
            {% else %}
              <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_number }}" class="page__btn">{{ page_number }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.next_page_number }}" class="page__btn"><i class="bi bi-chevron-right" style="font-size: 15px; margin-left: 10px;"></i></a>
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.paginator.num_pages }}" class="page_btn"><i class="bi bi-chevron-double-right" style="font-size: 15px;"></i></a>
        {% endif %}
      </div>
    </div>

    {% comment %} search {% endcomment %}
    <div class="posts__post--searchwrap">
      <form action="{% url 'posts:search' %}" method="GET">
        <div class="posts--post--searchbox">
          <select name="search_option" id="" class="posts__post--searchlist">
            <option value="title">제목</option>
            <option value="author">작성자</option>
            <option value="content">내용</option>
            <option value="title_content">제목+내용</option>
          </select>
          <input type="text" name="q" value="{{ query|default:'' }}" placeholder="검색어를 입력하세요" class="posts__post--searchbar dark:tw-ring-blue-400 tw-ring-opacity-50">
          <button type="submit" class="posts__post--search"><i class="bi bi-search"></i></button>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

{% block script %}
{% endblock script %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% load static %}
{% load highlight_filter %}
{% load custom_filters %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/posts/postsindex.css' %}">
{% endblock style %}

{% block content %}
<section class="bg-white-0 dark:bg-gray-900">
  <div class="posts__index--warp">
    <div class="posts__index--header">
      <h1 class="posts__index--title dark:text-white">커뮤니티</h1>
      <a href="{% url 'posts:create' %}">
        <button type="button" class="posts__post--writebtn text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">글작성</button>
      </a>
    </div>
    <div class="posts__posts--listbox dark:text-white"> 
      <ul class="posts__posts--list">
        <li class="posts__posts--index">
          <p class="text1" style="width: 5%;">번호</p>
          <p class="text1" style="width: 10%;"></p>
          <p class="text1" style="width: 38%;">제목</p>
          <p class="text1" style="width: 15%;">작성자</p>
          <p class="text1" style="width: 15%;">작성일</p>
          <p class="text1" style="width: 8.5%;">추천</p>
          <p class="text1" style="width: 8.5%;">조회수</p>
        </li>
      </ul>
      <ul class="posts__posts--list">
        {% for post in page_obj %}
          <a href="{% url 'posts:detail' post.pk %}">
            <li class="posts__post--item {% if forloop.last %}last{% endif %}">
              <p class="posts__number text-center" style="width: 5%;">{{ post.pk }}</p>
              <p class="posts__number text-center" style="width: 10%;">[{{post.category}}]</p>
              {% if search_option == 'title' %}
                <p class="posts__title">{{ post.title|highlight:query|safe }}<span class="posts__index--titlecnt">{% if post.postcomment_set.count != 0 %}[{{ post.postcomment_set.count }}]{% else %}{% endif %}</span></p>
              {% else %}
                <p class="posts__title">{{ post.title }}<span class="posts__index--titlecnt">{% if post.postcomment_set.count != 0 %}[{{ post.postcomment_set.count }}]{% else %}{% endif %}</span></p>
              {% endif %}
              {% if search_option == 'author' %}
                <p class="posts__user text-center" style="width: 15%;">{{ post.user.username|highlight:query|safe }}</p>
              {% else %}
                <p class="posts__user text-center" style="width: 15%;">{{ post.user.username }}</p>
              {% endif %}
              <p class="posts__created text-center" style="width: 15%;">{{ post.created_at|date:"Y. m. d" }}</p>
              <p class="posts__created text-center" style="width: 8.5%;">{{ post.like_users.count }}</p>
              <p class="posts__created text-center" style="width: 8.5%;">{{ post.view_count }}</p>
            </li>
          </a>
        {% endfor %}
      </ul>
    </div>
    {% comment %} paginator {% endcomment %}
    <div class="pagination mt-4">
      <div class="mx-auto dark:text-white">
        {% if page_obj.has_previous %}
          <a href="?search_option={{ search_option }}&q={{ query }}&page=1" class="page__btn"><i class="bi bi-chevron-double-left" style="font-size: 15px;"></i></a>
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.previous_page_number }}" class="page__btn"><i class="bi bi-chevron-left" style="font-size: 15px; margin-right: 10px;"></i></a>
        {% endif %}
        {% for page_number in page_obj.paginator.page_range %}
          {% if page_number >= page_obj.number|add:'-5' and page_number <= page_obj.number|add:'4' %}
            {% if page_number == page_obj.number %}
              <span class="page__btn pagination__link--active">{{ page_number }}</span>
            {% else %}
              <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_number }}" class="page__btn">{{ page_number }}</a>
            {% endif %}
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.next_page_number }}" class="page__btn"><i class="bi bi-chevron-right" style="font-size: 15px; margin-left: 10px;"></i></a>
          <a href="?search_option={{ search_option }}&q={{ query }}&page={{ page_obj.paginator.num_pages }}" class="page_btn"><i class="bi bi-chevron-double-right" style="font-size: 15px;"></i></a>
        {% endif %}
      </div>
    </div>

    {% comment %} search {% endcomment %}
    <div class="posts__post--searchwrap">
      <form action="{% url 'posts:search' %}" method="GET">
        <div class="posts--post--searchbox">
          <select name="search_option" id="" class="posts__post--searchlist">
            <option value="title">제목</option>
            <option value="author">작성자</option>
            <option value="content">내용</option>
            <option value="title_content">제목+내용</option>
          </select>
          <input type="text" name="q" value="{{ query|default:'' }}" placeholder="검색어를 입력하세요" class="posts__post--searchbar dark:tw-ring-blue-400 tw-ring-opacity-50">
          <button type="submit" class="posts__post--search"><i class="bi bi-search"></i></button>
        </div>
      </form>
    </div>
  </div>
</section>
{% endblock content %}

{% block script %}
{% endblock script %}